/*
Deployment script for DatabaseProjectFINALPROJECT

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "DatabaseProjectFINALPROJECT"
:setvar DefaultFilePrefix "DatabaseProjectFINALPROJECT"
:setvar DefaultDataPath "/var/opt/mssql/data/"
:setvar DefaultLogPath "/var/opt/mssql/data/"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating database $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [$(DatabaseName)], FILENAME = N'$(DefaultDataPath)$(DefaultFilePrefix)_Primary.mdf')
    LOG ON (NAME = [$(DatabaseName)_log], FILENAME = N'$(DefaultLogPath)$(DefaultFilePrefix)_Primary.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY NONE,
                DATE_CORRELATION_OPTIMIZATION OFF,
                DISABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF),
                MEMORY_OPTIMIZED_ELEVATE_TO_SNAPSHOT = OFF,
                DELAYED_DURABILITY = DISABLED 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET QUERY_STORE (QUERY_CAPTURE_MODE = ALL, OPERATION_MODE = READ_WRITE, DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_PLANS_PER_QUERY = 200, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 367), MAX_STORAGE_SIZE_MB = 100) 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
        ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
        ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET TEMPORAL_HISTORY_RETENTION ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ACCELERATED_DATABASE_RECOVERY = OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
PRINT N'Creating Table [dbo].[Appointments]...';


GO
CREATE TABLE [dbo].[Appointments] (
    [appointment_id]   INT          IDENTITY (1, 1) NOT NULL,
    [appointment_date] DATE         NOT NULL,
    [appointment_time] TIME (0)     NOT NULL,
    [reason]           TEXT         NOT NULL,
    [status]           VARCHAR (50) NOT NULL,
    [client_id]        INT          NOT NULL,
    [pet_id]           INT          NOT NULL,
    [staff_id]         INT          NOT NULL,
    CONSTRAINT [PK_Appointments] PRIMARY KEY CLUSTERED ([appointment_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Clients]...';


GO
CREATE TABLE [dbo].[Clients] (
    [client_id]     INT           IDENTITY (1, 1) NOT NULL,
    [first_name]    VARCHAR (50)  NOT NULL,
    [last_name]     VARCHAR (50)  NOT NULL,
    [email]         VARCHAR (50)  NOT NULL,
    [phone_number]  CHAR (11)     NOT NULL,
    [address]       VARCHAR (MAX) NULL,
    [registered_at] DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED ([client_id] ASC),
    CONSTRAINT [UK_Clients_Phone] UNIQUE NONCLUSTERED ([phone_number] ASC)
);


GO
PRINT N'Creating Index [dbo].[Clients].[UK_Clients_Email]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Clients_Email]
    ON [dbo].[Clients]([email] ASC);


GO
PRINT N'Creating Table [dbo].[Medical_Records]...';


GO
CREATE TABLE [dbo].[Medical_Records] (
    [record_id]  INT            IDENTITY (1, 1) NOT NULL,
    [visit_date] DATE           NOT NULL,
    [diagnosis]  TEXT           NULL,
    [weight_kg]  DECIMAL (5, 2) NOT NULL,
    [notes]      TEXT           NULL,
    [created_at] DATETIME2 (0)  NOT NULL,
    [pet_id]     INT            NOT NULL,
    [staff_id]   INT            NOT NULL,
    CONSTRAINT [PK_Medical_Records] PRIMARY KEY CLUSTERED ([record_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Medications]...';


GO
CREATE TABLE [dbo].[Medications] (
    [medication_id]   INT           IDENTITY (1, 1) NOT NULL,
    [drug_name]       VARCHAR (100) NOT NULL,
    [standard_dosage] VARCHAR (100) NOT NULL,
    [unit]            VARCHAR (50)  NOT NULL,
    [description]     TEXT          NULL,
    CONSTRAINT [PK_Medications] PRIMARY KEY CLUSTERED ([medication_id] ASC),
    CONSTRAINT [UK_Medications_drugname] UNIQUE NONCLUSTERED ([drug_name] ASC)
);


GO
PRINT N'Creating Table [dbo].[Pets]...';


GO
CREATE TABLE [dbo].[Pets] (
    [pet_id]    INT          IDENTITY (1, 1) NOT NULL,
    [name]      VARCHAR (50) NOT NULL,
    [species]   VARCHAR (50) NOT NULL,
    [breed]     VARCHAR (50) NULL,
    [sex]       CHAR (1)     NOT NULL,
    [birthdate] DATE         NOT NULL,
    [Is_active] BIT          NOT NULL,
    [client_id] INT          NOT NULL,
    CONSTRAINT [PK_Pets] PRIMARY KEY CLUSTERED ([pet_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Prescriptions]...';


GO
CREATE TABLE [dbo].[Prescriptions] (
    [prescription_id] INT          IDENTITY (1, 1) NOT NULL,
    [dosage_given]    VARCHAR (50) NOT NULL,
    [duration_days]   SMALLINT     NOT NULL,
    [Instructions]    TEXT         NULL,
    [record_id]       INT          NOT NULL,
    [medication_id]   INT          NOT NULL,
    CONSTRAINT [PK_Prescriptions] PRIMARY KEY CLUSTERED ([prescription_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Staff]...';


GO
CREATE TABLE [dbo].[Staff] (
    [staff_id]       INT          IDENTITY (1, 1) NOT NULL,
    [first_name]     VARCHAR (50) NOT NULL,
    [last_name]      VARCHAR (50) NOT NULL,
    [role]           VARCHAR (50) NOT NULL,
    [email]          VARCHAR (50) NOT NULL,
    [phone]          CHAR (11)    NOT NULL,
    [license_number] VARCHAR (50) NULL,
    [is_active]      BIT          NOT NULL,
    CONSTRAINT [PK_Staff] PRIMARY KEY CLUSTERED ([staff_id] ASC),
    CONSTRAINT [UK_Staff_Phone] UNIQUE NONCLUSTERED ([phone] ASC)
);


GO
PRINT N'Creating Index [dbo].[Staff].[UK_Staff_LicenseNumber]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Staff_LicenseNumber]
    ON [dbo].[Staff]([license_number] ASC);


GO
PRINT N'Creating Index [dbo].[Staff].[UK_Staff_Email]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Staff_Email]
    ON [dbo].[Staff]([email] ASC);


GO
PRINT N'Creating Table [dbo].[Vaccination_Schedule]...';


GO
CREATE TABLE [dbo].[Vaccination_Schedule] (
    [schedule_id]   INT          IDENTITY (1, 1) NOT NULL,
    [vaccine_name]  VARCHAR (50) NOT NULL,
    [last_given]    DATE         NOT NULL,
    [next_due]      DATE         NOT NULL,
    [reminder_sent] BIT          NOT NULL,
    [pet_id]        INT          NOT NULL,
    [record_id]     INT          NOT NULL,
    CONSTRAINT [PK_Vaccination_Schedule] PRIMARY KEY CLUSTERED ([schedule_id] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Appointments_status]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [DF_Appointments_status] DEFAULT ('Scheduled') FOR [status];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Clients_registered_at]...';


GO
ALTER TABLE [dbo].[Clients]
    ADD CONSTRAINT [DF_Clients_registered_at] DEFAULT (getdate()) FOR [registered_at];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Medical_Records_created_at]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [DF_Medical_Records_created_at] DEFAULT (getdate()) FOR [created_at];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Pets_Is_active]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [DF_Pets_Is_active] DEFAULT ((1)) FOR [Is_active];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Staff_is_active]...';


GO
ALTER TABLE [dbo].[Staff]
    ADD CONSTRAINT [DF_Staff_is_active] DEFAULT ((1)) FOR [is_active];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Vaccination_Schedule_reminder_sent]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [DF_Vaccination_Schedule_reminder_sent] DEFAULT ((0)) FOR [reminder_sent];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointments_Pets]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [FK_Appointments_Pets] FOREIGN KEY ([pet_id]) REFERENCES [dbo].[Pets] ([pet_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointments_Staff]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [FK_Appointments_Staff] FOREIGN KEY ([staff_id]) REFERENCES [dbo].[Staff] ([staff_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointments_Clients]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [FK_Appointments_Clients] FOREIGN KEY ([client_id]) REFERENCES [dbo].[Clients] ([client_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Medical_Records_Pets]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [FK_Medical_Records_Pets] FOREIGN KEY ([pet_id]) REFERENCES [dbo].[Pets] ([pet_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Medical_Records_Staff]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [FK_Medical_Records_Staff] FOREIGN KEY ([staff_id]) REFERENCES [dbo].[Staff] ([staff_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Pets_Clients]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [FK_Pets_Clients] FOREIGN KEY ([client_id]) REFERENCES [dbo].[Clients] ([client_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Prescriptions_Medications]...';


GO
ALTER TABLE [dbo].[Prescriptions]
    ADD CONSTRAINT [FK_Prescriptions_Medications] FOREIGN KEY ([medication_id]) REFERENCES [dbo].[Medications] ([medication_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Prescriptions_Medical_Records]...';


GO
ALTER TABLE [dbo].[Prescriptions]
    ADD CONSTRAINT [FK_Prescriptions_Medical_Records] FOREIGN KEY ([record_id]) REFERENCES [dbo].[Medical_Records] ([record_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Vaccination_Schedule_Pets]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [FK_Vaccination_Schedule_Pets] FOREIGN KEY ([pet_id]) REFERENCES [dbo].[Pets] ([pet_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Vaccination_Schedule_Medical_Records]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [FK_Vaccination_Schedule_Medical_Records] FOREIGN KEY ([record_id]) REFERENCES [dbo].[Medical_Records] ([record_id]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_Appointments_status]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [CK_Appointments_status] CHECK ([status]='Cancelled' OR [status]='Completed' OR [status]='Scheduled');


GO
PRINT N'Creating Check Constraint [dbo].[CK_Medical_Records_Weight]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [CK_Medical_Records_Weight] CHECK ([weight_kg]>(0));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Medical_Records_visitdate]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [CK_Medical_Records_visitdate] CHECK ([visit_date]<=getdate());


GO
PRINT N'Creating Check Constraint [dbo].[CK_Medications_unit]...';


GO
ALTER TABLE [dbo].[Medications]
    ADD CONSTRAINT [CK_Medications_unit] CHECK ([unit]='capsule' OR [unit]='tablet' OR [unit]='ml' OR [unit]='mg');


GO
PRINT N'Creating Check Constraint [dbo].[CK_Pets_Sex]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [CK_Pets_Sex] CHECK ([sex]='F' OR [sex]='M');


GO
PRINT N'Creating Check Constraint [dbo].[CK_Pets_IsActive]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [CK_Pets_IsActive] CHECK ([is_active]=(1) OR [is_active]=(0));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Pets_DateNotFuture]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [CK_Pets_DateNotFuture] CHECK ([birthdate]<getdate());


GO
PRINT N'Creating Check Constraint [dbo].[CK_Prescriptions_DurationDays]...';


GO
ALTER TABLE [dbo].[Prescriptions]
    ADD CONSTRAINT [CK_Prescriptions_DurationDays] CHECK ([duration_days]>(0));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Vaccination_Schedule_NextDue]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [CK_Vaccination_Schedule_NextDue] CHECK ([next_due]>[last_given]);


GO
PRINT N'Creating View [dbo].[ClientsPetsView]...';


GO
CREATE VIEW ClientsPetsView 
AS
SELECT 
       c.first_name + ' ' + c.last_name AS client_name,
       c.phone_number,
       p.name AS pet_name, p.species, p.breed, p.sex
FROM Clients c JOIN Pets p 
ON c.client_id = p.client_id
GO
PRINT N'Creating Procedure [dbo].[DeleteClientAndPets]...';


GO
CREATE PROC DeleteClientAndPets
    @ClientID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT client_id FROM Clients WHERE client_id = @ClientID)
    BEGIN
        RAISERROR('Client doesnt exist.', 16, 1);
        RETURN
    END

    BEGIN TRY
        BEGIN TRANSACTION;

        DELETE FROM Pets 
        WHERE client_id = @ClientID;

        DELETE FROM Clients 
        WHERE client_id = @ClientID;

        COMMIT TRANSACTION;
        PRINT 'Client and associated pets deleted successfully.';
    END TRY

    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspInsertClientsPets]...';


GO
CREATE PROC uspInsertClientsPets
    @Fname VARCHAR(50),
    @Lname VARCHAR(50),
    @Email VARCHAR(50),
    @Phone CHAR(11),
    @Address VARCHAR(MAX) = NULL,
    @Registered DATETIME = NULL,
    @PetName VARCHAR(50),
    @PetSpecies VARCHAR(50),
    @PetBreed VARCHAR(50) = NULL,
    @PetGender CHAR(1),
    @PetDOB DATE,
    @IsActive BIT = NULL

 AS
 BEGIN 
    SET NOCOUNT ON;

    IF LEFT((@Phone), 1) = '0'
        BEGIN 
            SET @Phone = SUBSTRING(@Phone, 2, LEN(@Phone));
        END

    SET @IsActive = ISNULL (@IsActive, 1);
    SET @Registered = ISNULL (@Registered, GETDATE());

        BEGIN TRY
            BEGIN TRANSACTION

            INSERT Clients 
            VALUES (@Fname, @Lname, @Email, @Phone, @Address, @Registered);

            DECLARE @OwnerID INT = SCOPE_IDENTITY();

            INSERT Pets 
            VALUES (@PetName, @PetSpecies, @PetBreed, @PetGender, @PetDOB,@IsActive, @OwnerID);

            COMMIT TRANSACTION
            PRINT ('Client and pet records inserted successfully.');
        END TRY

        BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            THROW;
        END CATCH
 END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateClientsPets]...';


GO
CREATE PROC uspUpdateClientsPets
    @ClientID INT,
    @Fname VARCHAR(50) = NULL,
    @Lname VARCHAR(50) = NULL,
    @Email VARCHAR(50) = NULL,
    @Phone CHAR(11) = NULL,
    @Address VARCHAR(MAX) = NULL,
    @Registered DATETIME = NULL,
    @PetID INT = NULL,
    @PetName VARCHAR(50) = NULL,
    @PetSpecies VARCHAR(50) = NULL,
    @PetBreed VARCHAR(50) = NULL,
    @PetGender CHAR(1) = NULL,
    @PetDOB DATE = NULL,
    @IsActive BIT = NULL

 AS
 BEGIN 
    SET NOCOUNT ON;

     IF @Phone IS NOT NULL AND LEFT((@Phone), 1) = '0'
        BEGIN 
            SET @Phone = SUBSTRING(@Phone, 2, LEN(@Phone)); 
        END

    IF NOT EXISTS (SELECT client_id FROM Clients WHERE client_id = @ClientID)
    BEGIN
       RAISERROR('Client does not exist, or The specified Pet does not belong to this Client, or Client or Pet does not exist.', 16, 1);
        RETURN;
    END

    IF @PetID IS NOT NULL 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM Pets WHERE pet_id = @PetID AND client_id = @ClientID )
        BEGIN
            RAISERROR('Client does not exist, or The specified Pet does not belong to this Client, or Client or Pet does not exist.', 16, 1);
            RETURN;
        END
    END
    
    BEGIN TRY
        BEGIN TRANSACTION

            UPDATE Clients
            SET first_name = ISNULL(@Fname, first_name),
                last_name = ISNULL(@Lname, last_name),
                email = ISNULL(@Email, email),
                phone_number = ISNULL(@Phone, phone_number),
                [address] = ISNULL(@Address, [address]),
                registered_at = ISNULL(@Registered, registered_at)
            WHERE client_id = @ClientID;

            IF @PetID IS NOT NULL
            BEGIN
                UPDATE Pets
                SET [name] = ISNULL(@PetName, [name]),
                    species = ISNULL(@PetSpecies, species),
                    breed = ISNULL(@PetBreed, breed),
                    sex = ISNULL(@PetGender, sex),
                    birthdate = ISNULL(@PetDOB, birthdate),
                    is_active = ISNULL(@IsActive, is_active)
                WHERE pet_id = @PetID;
            END 

            COMMIT TRANSACTION
            PRINT ('Records updated successfully.');

        END TRY

        BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            PRINT(ERROR_MESSAGE());
        END CATCH
 END
GO
DECLARE @VarDecimalSupported AS BIT;

SELECT @VarDecimalSupported = 0;

IF ((ServerProperty(N'EngineEdition') = 3)
    AND (((@@microsoftversion / power(2, 24) = 9)
          AND (@@microsoftversion & 0xffff >= 3024))
         OR ((@@microsoftversion / power(2, 24) = 10)
             AND (@@microsoftversion & 0xffff >= 1600))))
    SELECT @VarDecimalSupported = 1;

IF (@VarDecimalSupported > 0)
    BEGIN
        EXECUTE sp_db_vardecimal_storage_format N'$(DatabaseName)', 'ON';
    END


GO
PRINT N'Update complete.';


GO
