/*
Deployment script for DatabaseProjectFINALPROJECT

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/


USE [master];
GO

IF (DB_ID(N'VETCLINICFINALPROJECT') IS NOT NULL)
BEGIN
    ALTER DATABASE [VETCLINICFINALPROJECT]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [VETCLINICFINALPROJECT];
END
GO

PRINT N'Creating database VETCLINICFINALPROJECT...';
GO
CREATE DATABASE [VETCLINICFINALPROJECT];
GO

USE [VETCLINICFINALPROJECT];


GO
PRINT N'Creating Table [dbo].[Appointments]...';


GO
CREATE TABLE [dbo].[Appointments] (
    [appointment_id]   INT           IDENTITY (1, 1) NOT NULL,
    [appointment_date] DATE          NOT NULL,
    [appointment_time] TIME (0)      NOT NULL,
    [reason]           VARCHAR (MAX) NOT NULL,
    [status]           VARCHAR (50)  NOT NULL,
    [client_id]        INT           NOT NULL,
    [pet_id]           INT           NOT NULL,
    [staff_id]         INT           NOT NULL,
    CONSTRAINT [PK_Appointments] PRIMARY KEY CLUSTERED ([appointment_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[AuditLog]...';


GO
CREATE TABLE [dbo].[AuditLog] (
    [audit_id]       INT            IDENTITY (1, 1) NOT NULL,
    [table_name]     VARCHAR (50)   NOT NULL,
    [operation_type] VARCHAR (10)   NOT NULL,
    [record_id]      INT            NOT NULL,
    [column_changed] VARCHAR (50)   NULL,
    [old_value]      NVARCHAR (MAX) NULL,
    [new_value]      NVARCHAR (MAX) NULL,
    [changed_by]     VARCHAR (50)   NOT NULL,
    [changed_at]     DATETIME2 (0)  NOT NULL,
    PRIMARY KEY CLUSTERED ([audit_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Clients]...';


GO
CREATE TABLE [dbo].[Clients] (
    [client_id]     INT           IDENTITY (1, 1) NOT NULL,
    [first_name]    VARCHAR (50)  NOT NULL,
    [last_name]     VARCHAR (50)  NOT NULL,
    [email]         VARCHAR (50)  NOT NULL,
    [phone_number]  CHAR (11)     NOT NULL,
    [address]       VARCHAR (MAX) NULL,
    [registered_at] DATETIME2 (0) NOT NULL,
    CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED ([client_id] ASC),
    CONSTRAINT [UK_Clients_Phone] UNIQUE NONCLUSTERED ([phone_number] ASC)
);


GO
PRINT N'Creating Index [dbo].[Clients].[UK_Clients_Email]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Clients_Email]
    ON [dbo].[Clients]([email] ASC);


GO
PRINT N'Creating Table [dbo].[Medical_Records]...';


GO
CREATE TABLE [dbo].[Medical_Records] (
    [record_id]  INT            IDENTITY (1, 1) NOT NULL,
    [visit_date] DATE           NOT NULL,
    [diagnosis]  VARCHAR (MAX)  NULL,
    [weight_kg]  DECIMAL (5, 2) NOT NULL,
    [notes]      VARCHAR (MAX)  NULL,
    [created_at] DATETIME2 (0)  NOT NULL,
    [pet_id]     INT            NOT NULL,
    [staff_id]   INT            NOT NULL,
    CONSTRAINT [PK_Medical_Records] PRIMARY KEY CLUSTERED ([record_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Medications]...';


GO
CREATE TABLE [dbo].[Medications] (
    [medication_id]   INT           IDENTITY (1, 1) NOT NULL,
    [drug_name]       VARCHAR (100) NOT NULL,
    [standard_dosage] VARCHAR (100) NOT NULL,
    [unit]            VARCHAR (50)  NOT NULL,
    [description]     VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Medications] PRIMARY KEY CLUSTERED ([medication_id] ASC),
    CONSTRAINT [UK_Medications_drugname] UNIQUE NONCLUSTERED ([drug_name] ASC)
);


GO
PRINT N'Creating Table [dbo].[Pets]...';


GO
CREATE TABLE [dbo].[Pets] (
    [pet_id]    INT          IDENTITY (1, 1) NOT NULL,
    [name]      VARCHAR (50) NOT NULL,
    [species]   VARCHAR (50) NOT NULL,
    [breed]     VARCHAR (50) NULL,
    [sex]       CHAR (1)     NOT NULL,
    [birthdate] DATE         NOT NULL,
    [Is_active] BIT          NOT NULL,
    [client_id] INT          NOT NULL,
    CONSTRAINT [PK_Pets] PRIMARY KEY CLUSTERED ([pet_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Prescriptions]...';


GO
CREATE TABLE [dbo].[Prescriptions] (
    [prescription_id] INT           IDENTITY (1, 1) NOT NULL,
    [dosage_given]    VARCHAR (50)  NOT NULL,
    [duration_days]   SMALLINT      NOT NULL,
    [Instructions]    VARCHAR (MAX) NULL,
    [record_id]       INT           NOT NULL,
    [medication_id]   INT           NOT NULL,
    CONSTRAINT [PK_Prescriptions] PRIMARY KEY CLUSTERED ([prescription_id] ASC)
);


GO
PRINT N'Creating Table [dbo].[Staff]...';


GO
CREATE TABLE [dbo].[Staff] (
    [staff_id]       INT           IDENTITY (1, 1) NOT NULL,
    [first_name]     VARCHAR (50)  NOT NULL,
    [last_name]      VARCHAR (50)  NOT NULL,
    [role]           VARCHAR (50)  NOT NULL,
    [email]          VARCHAR (100) NOT NULL,
    [phone]          CHAR (11)     NOT NULL,
    [license_number] VARCHAR (50)  NULL,
    [is_active]      BIT           NOT NULL,
    CONSTRAINT [PK_Staff] PRIMARY KEY CLUSTERED ([staff_id] ASC),
    CONSTRAINT [UK_Staff_Phone] UNIQUE NONCLUSTERED ([phone] ASC)
);


GO
PRINT N'Creating Index [dbo].[Staff].[UK_Staff_Email]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Staff_Email]
    ON [dbo].[Staff]([email] ASC);


GO
PRINT N'Creating Index [dbo].[Staff].[UK_Staff_LicenseNumber]...';


GO
CREATE UNIQUE NONCLUSTERED INDEX [UK_Staff_LicenseNumber]
    ON [dbo].[Staff]([license_number] ASC) WHERE ([license_number] IS NOT NULL);


GO
PRINT N'Creating Table [dbo].[Vaccination_Schedule]...';


GO
CREATE TABLE [dbo].[Vaccination_Schedule] (
    [schedule_id]   INT          IDENTITY (1, 1) NOT NULL,
    [vaccine_name]  VARCHAR (50) NOT NULL,
    [last_given]    DATE         NOT NULL,
    [next_due]      DATE         NOT NULL,
    [reminder_sent] BIT          NOT NULL,
    [pet_id]        INT          NOT NULL,
    [record_id]     INT          NOT NULL,
    CONSTRAINT [PK_Vaccination_Schedule] PRIMARY KEY CLUSTERED ([schedule_id] ASC)
);


GO
PRINT N'Creating Default Constraint [dbo].[DF_Appointments_status]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [DF_Appointments_status] DEFAULT ('Scheduled') FOR [status];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[AuditLog]...';


GO
ALTER TABLE [dbo].[AuditLog]
    ADD DEFAULT (getdate()) FOR [changed_at];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[AuditLog]...';


GO
ALTER TABLE [dbo].[AuditLog]
    ADD DEFAULT (suser_sname()) FOR [changed_by];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Clients_registered_at]...';


GO
ALTER TABLE [dbo].[Clients]
    ADD CONSTRAINT [DF_Clients_registered_at] DEFAULT (getdate()) FOR [registered_at];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Medical_Records_created_at]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [DF_Medical_Records_created_at] DEFAULT (getdate()) FOR [created_at];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Pets_Is_active]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [DF_Pets_Is_active] DEFAULT ((1)) FOR [Is_active];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Staff_is_active]...';


GO
ALTER TABLE [dbo].[Staff]
    ADD CONSTRAINT [DF_Staff_is_active] DEFAULT ((1)) FOR [is_active];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Vaccination_Schedule_reminder_sent]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [DF_Vaccination_Schedule_reminder_sent] DEFAULT ((0)) FOR [reminder_sent];


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointments_Pets]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [FK_Appointments_Pets] FOREIGN KEY ([pet_id]) REFERENCES [dbo].[Pets] ([pet_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointments_Clients]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [FK_Appointments_Clients] FOREIGN KEY ([client_id]) REFERENCES [dbo].[Clients] ([client_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Appointments_Staff]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [FK_Appointments_Staff] FOREIGN KEY ([staff_id]) REFERENCES [dbo].[Staff] ([staff_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Medical_Records_Pets]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [FK_Medical_Records_Pets] FOREIGN KEY ([pet_id]) REFERENCES [dbo].[Pets] ([pet_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Medical_Records_Staff]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [FK_Medical_Records_Staff] FOREIGN KEY ([staff_id]) REFERENCES [dbo].[Staff] ([staff_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Pets_Clients]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [FK_Pets_Clients] FOREIGN KEY ([client_id]) REFERENCES [dbo].[Clients] ([client_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Prescriptions_Medical_Records]...';


GO
ALTER TABLE [dbo].[Prescriptions]
    ADD CONSTRAINT [FK_Prescriptions_Medical_Records] FOREIGN KEY ([record_id]) REFERENCES [dbo].[Medical_Records] ([record_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Prescriptions_Medications]...';


GO
ALTER TABLE [dbo].[Prescriptions]
    ADD CONSTRAINT [FK_Prescriptions_Medications] FOREIGN KEY ([medication_id]) REFERENCES [dbo].[Medications] ([medication_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Vaccination_Schedule_Medical_Records]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [FK_Vaccination_Schedule_Medical_Records] FOREIGN KEY ([record_id]) REFERENCES [dbo].[Medical_Records] ([record_id]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Vaccination_Schedule_Pets]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [FK_Vaccination_Schedule_Pets] FOREIGN KEY ([pet_id]) REFERENCES [dbo].[Pets] ([pet_id]);


GO
PRINT N'Creating Check Constraint [dbo].[CK_Appointments_status]...';


GO
ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [CK_Appointments_status] CHECK ([status]='Cancelled' OR [status]='Completed' OR [status]='Scheduled');


GO
PRINT N'Creating Check Constraint [dbo].[CK_Medical_Records_Weight]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [CK_Medical_Records_Weight] CHECK ([weight_kg]>(0));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Medical_Records_visitdate]...';


GO
ALTER TABLE [dbo].[Medical_Records]
    ADD CONSTRAINT [CK_Medical_Records_visitdate] CHECK ([visit_date]<=getdate());


GO
PRINT N'Creating Check Constraint [dbo].[CK_Medications_unit]...';


GO
ALTER TABLE [dbo].[Medications]
    ADD CONSTRAINT [CK_Medications_unit] CHECK ([unit]='capsule' OR [unit]='tablet' OR [unit]='ml' OR [unit]='mg');


GO
PRINT N'Creating Check Constraint [dbo].[CK_Pets_IsActive]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [CK_Pets_IsActive] CHECK ([is_active]=(1) OR [is_active]=(0));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Pets_Sex]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [CK_Pets_Sex] CHECK ([sex]='F' OR [sex]='M');


GO
PRINT N'Creating Check Constraint [dbo].[CK_Pets_DateNotFuture]...';


GO
ALTER TABLE [dbo].[Pets]
    ADD CONSTRAINT [CK_Pets_DateNotFuture] CHECK ([birthdate]<getdate());


GO
PRINT N'Creating Check Constraint [dbo].[CK_Prescriptions_DurationDays]...';


GO
ALTER TABLE [dbo].[Prescriptions]
    ADD CONSTRAINT [CK_Prescriptions_DurationDays] CHECK ([duration_days]>(0));


GO
PRINT N'Creating Check Constraint [dbo].[CK_Vaccination_Schedule_NextDue]...';


GO
ALTER TABLE [dbo].[Vaccination_Schedule]
    ADD CONSTRAINT [CK_Vaccination_Schedule_NextDue] CHECK ([next_due]>[last_given]);


GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Clients]...';


GO

CREATE TRIGGER TRIGGER_ALL_Clients ON Clients
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Action VARCHAR(20);

    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
        SET @Action = 'UPDATE';
    ELSE IF EXISTS (SELECT 1 FROM inserted)
        SET @Action = 'INSERT';
    ELSE
        SET @Action = 'DELETE';

    IF @Action = 'INSERT'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Clients', 'INSERT', client_id,
               CONCAT('FirstName: ', first_name, '; LastName: ', last_name, '; Email: ', email,
                      '; Phone: ', phone_number, '; Address: ', ISNULL(address,''))
        FROM inserted;
    END

    IF @Action = 'UPDATE'
    BEGIN
        IF UPDATE(first_name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Clients', 'UPDATE', i.client_id, 'first_name', d.first_name, i.first_name
            FROM deleted d JOIN inserted i ON d.client_id = i.client_id
            WHERE d.first_name <> i.first_name;

        IF UPDATE(last_name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Clients', 'UPDATE', i.client_id, 'last_name', d.last_name, i.last_name
            FROM deleted d JOIN inserted i ON d.client_id = i.client_id
            WHERE d.last_name <> i.last_name;

        IF UPDATE(email)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Clients', 'UPDATE', i.client_id, 'email', d.email, i.email
            FROM deleted d JOIN inserted i ON d.client_id = i.client_id
            WHERE d.email <> i.email;

        IF UPDATE(phone_number)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Clients', 'UPDATE', i.client_id, 'phone_number', d.phone_number, i.phone_number
            FROM deleted d JOIN inserted i ON d.client_id = i.client_id
            WHERE d.phone_number <> i.phone_number;

        IF UPDATE(address)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Clients', 'UPDATE', i.client_id, 'address', d.address, i.address
            FROM deleted d JOIN inserted i ON d.client_id = i.client_id
            WHERE ISNULL(d.address,'') <> ISNULL(i.address,'');
    END

    IF @Action = 'DELETE'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Clients', 'DELETE', client_id,
               CONCAT('FirstName: ', first_name, '; LastName: ', last_name, '; Email: ', email,
                      '; Phone: ', phone_number, '; Address: ', ISNULL(address,''))
        FROM deleted;
    END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Medications]...';


GO

CREATE TRIGGER TRIGGER_ALL_Medications ON Medications
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Action VARCHAR(20);

    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
        SET @Action = 'UPDATE';
    ELSE IF EXISTS (SELECT 1 FROM inserted)
        SET @Action = 'INSERT';
    ELSE
        SET @Action = 'DELETE';

    IF @Action = 'INSERT'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Medications', 'INSERT', medication_id,
               CONCAT('Drugname: ', drug_name, '; StandardDosage: ', standard_dosage,
                      '; Unit: ', unit, '; Description: ', ISNULL(description,''))
        FROM inserted;
    END

    IF @Action = 'UPDATE'
    BEGIN
        IF UPDATE(drug_name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Medications', 'UPDATE', i.medication_id, 'drug_name', d.drug_name, i.drug_name
            FROM deleted d JOIN inserted i ON d.medication_id = i.medication_id
            WHERE d.drug_name <> i.drug_name;

        IF UPDATE(standard_dosage)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Medications', 'UPDATE', i.medication_id, 'standard_dosage', d.standard_dosage, i.standard_dosage
            FROM deleted d JOIN inserted i ON d.medication_id = i.medication_id
            WHERE d.standard_dosage <> i.standard_dosage;

        IF UPDATE(unit)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Medications', 'UPDATE', i.medication_id, 'unit', d.unit, i.unit
            FROM deleted d JOIN inserted i ON d.medication_id = i.medication_id
            WHERE d.unit <> i.unit;

        IF UPDATE(description)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Medications', 'UPDATE', i.medication_id, 'description', d.description, i.description
            FROM deleted d JOIN inserted i ON d.medication_id = i.medication_id
            WHERE ISNULL(d.description,'') <> ISNULL(i.description,'');
    END

    IF @Action = 'DELETE'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, old_value)
        SELECT 'Medications', 'DELETE', medication_id,
               CONCAT('Drugname: ', drug_name, '; StandardDosage: ', standard_dosage,
                      '; Unit: ', unit, '; Description: ', ISNULL(description,''))
        FROM deleted;
    END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Pets]...';


GO

CREATE TRIGGER TRIGGER_ALL_Pets ON Pets
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Action VARCHAR(20);

    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
        SET @Action = 'UPDATE';
    ELSE IF EXISTS (SELECT 1 FROM inserted)
        SET @Action = 'INSERT';
    ELSE
        SET @Action = 'DELETE';

    IF @Action = 'INSERT'
    BEGIN
        INSERT AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Pets', 'INSERT', pet_id,
               CONCAT('PetName: ', [name], '; Species: ', species, '; Breed: ', ISNULL(breed,''),
                      '; Sex: ', sex, '; Birth: ', birthdate, '; IsActive: ', is_active,
                      '; clientID: ', client_id)
        FROM inserted;
    END

    IF @Action = 'UPDATE'
    BEGIN
        IF UPDATE(name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'name', d.name, i.name
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE d.name <> i.name;

        IF UPDATE(species)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'species', d.species, i.species
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE d.species <> i.species;

        IF UPDATE(breed)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'breed', d.breed, i.breed
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE ISNULL(d.breed,'') <> ISNULL(i.breed,'');

        IF UPDATE(sex)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'sex', d.sex, i.sex
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE d.sex <> i.sex;

        IF UPDATE(birthdate)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'birthdate', CONVERT(VARCHAR, d.birthdate, 120), CONVERT(VARCHAR, i.birthdate, 120)
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE d.birthdate <> i.birthdate;

        IF UPDATE(is_active)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'is_active', d.is_active, i.is_active
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE d.is_active <> i.is_active;

        IF UPDATE(client_id)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Pets', 'UPDATE', i.pet_id, 'client_id', d.client_id, i.client_id
            FROM deleted d JOIN inserted i ON d.pet_id = i.pet_id
            WHERE d.client_id <> i.client_id;
    END

    IF @Action = 'DELETE'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, old_value)
        SELECT 'Pets', 'DELETE', pet_id,
               CONCAT('PetName: ', [name], '; Species: ', species, '; Breed: ', ISNULL(breed,''),
                      '; Sex: ', sex, '; Birth: ', birthdate, '; IsActive: ', is_active,
                      '; clientID: ', client_id)
        FROM deleted;
    END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Prescriptions]...';


GO

CREATE TRIGGER TRIGGER_ALL_Prescriptions ON Prescriptions
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Action VARCHAR(20);

    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
        SET @Action = 'UPDATE';
    ELSE IF EXISTS (SELECT 1 FROM inserted)
        SET @Action = 'INSERT';
    ELSE
        SET @Action = 'DELETE';

    IF @Action = 'INSERT'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Prescriptions', 'INSERT', prescription_id,
               CONCAT('DosageGiven: ', dosage_given, '; DurationDays: ', duration_days,
                      '; Instructions: ', ISNULL(instructions,''),
                      '; RecordID: ', record_id, '; MedicationID: ', medication_id)
        FROM inserted;
    END

    IF @Action = 'UPDATE'
    BEGIN
        IF UPDATE(dosage_given)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Prescriptions', 'UPDATE', i.prescription_id, 'dosage_given', d.dosage_given, i.dosage_given
            FROM deleted d JOIN inserted i ON d.prescription_id = i.prescription_id
            WHERE d.dosage_given <> i.dosage_given;

        IF UPDATE(duration_days)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Prescriptions', 'UPDATE', i.prescription_id, 'duration_days', d.duration_days, i.duration_days
            FROM deleted d JOIN inserted i ON d.prescription_id = i.prescription_id
            WHERE d.duration_days <> i.duration_days;

        IF UPDATE(instructions)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Prescriptions', 'UPDATE', i.prescription_id, 'instructions', d.instructions, i.instructions
            FROM deleted d JOIN inserted i ON d.prescription_id = i.prescription_id
            WHERE ISNULL(d.instructions,'') <> ISNULL(i.instructions,'');

        IF UPDATE(medication_id)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Prescriptions', 'UPDATE', i.prescription_id, 'medication_id', d.medication_id, i.medication_id
            FROM deleted d JOIN inserted i ON d.prescription_id = i.prescription_id
            WHERE d.medication_id <> i.medication_id;
    END

    IF @Action = 'DELETE'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, old_value)
        SELECT 'Prescriptions', 'DELETE', prescription_id,
               CONCAT('DosageGiven: ', dosage_given, '; DurationDays: ', duration_days,
                      '; Instructions: ', ISNULL(instructions,''),
                      '; RecordID: ', record_id, '; MedicationID: ', medication_id)
        FROM deleted;
    END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Staff]...';


GO

CREATE TRIGGER TRIGGER_ALL_Staff ON Staff
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Action VARCHAR(20);

    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
        SET @Action = 'UPDATE';
    ELSE IF EXISTS (SELECT 1 FROM inserted)
        SET @Action = 'INSERT';
    ELSE
        SET @Action = 'DELETE';

    IF @Action = 'INSERT'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Staff', 'INSERT', staff_id,
               CONCAT('FirstName: ', first_name, '; LastName: ', last_name, '; Role: ', role,
                      '; Email: ', email, '; Phone: ', phone,
                      '; License#: ', ISNULL(license_number,''), '; IsActive: ', is_active)
        FROM inserted;
    END

    IF @Action = 'UPDATE'
    BEGIN
        IF UPDATE(first_name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'first_name', d.first_name, i.first_name
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE d.first_name <> i.first_name;

        IF UPDATE(last_name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'last_name', d.last_name, i.last_name
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE d.last_name <> i.last_name;

        IF UPDATE(role)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'role', d.role, i.role
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE d.role <> i.role;

        IF UPDATE(email)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'email', d.email, i.email
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE d.email <> i.email;

        IF UPDATE(phone)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'phone', d.phone, i.phone
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE d.phone <> i.phone;

        IF UPDATE(license_number)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'license_number', d.license_number, i.license_number
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE ISNULL(d.license_number,'') <> ISNULL(i.license_number,'');

        IF UPDATE(is_active)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Staff', 'UPDATE', i.staff_id, 'is_active', d.is_active, i.is_active
            FROM deleted d JOIN inserted i ON d.staff_id = i.staff_id
            WHERE d.is_active <> i.is_active;
    END

    IF @Action = 'DELETE'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Staff', 'DELETE', staff_id,
               CONCAT('FirstName: ', first_name, '; LastName: ', last_name, '; Role: ', role,
                      '; Email: ', email, '; Phone: ', phone,
                      '; License#: ', ISNULL(license_number,''), '; IsActive: ', is_active)
        FROM deleted;
    END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Appointments]...';



GO
CREATE TRIGGER TRIGGER_ALL_Appointments ON Appointments
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
   SET NOCOUNT ON;
   DECLARE @Action VARCHAR(20);
   IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
       SET @Action = 'UPDATE';
   ELSE IF EXISTS (SELECT 1 FROM inserted)
       SET @Action = 'INSERT';
   ELSE
       SET @Action = 'DELETE';


   IF @Action = 'INSERT'
   BEGIN
       INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
       SELECT 'Appointments', 'INSERT', appointment_id,
              CONCAT('Appointment_Date: ', appointment_date, '; Appointment_Time: ', appointment_time, '; Reason: ', reason,
                     '; Status: ', status, '; Client_Id: ', client_id, '; Pet_Id: ', pet_id, '; Staff_Id: ', staff_id)
       FROM inserted;
   END


   IF @Action = 'UPDATE'
   BEGIN
       IF UPDATE(appointment_date)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Appointment_Date', d.appointment_date, i.appointment_date
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.appointment_date <> i.appointment_date;


       IF UPDATE(appointment_time)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Appointment_Time', d.appointment_time, i.appointment_time
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.appointment_time <> i.appointment_time;


       IF UPDATE(reason)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
          SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Reason', d.reason, i.reason
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.reason <> i.reason;


       IF UPDATE(status)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Status', d.status, i.status
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.status <> i.status;


       IF UPDATE(client_id)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Client_Id', d.client_id, i.client_id
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.client_id <> i.client_id;


       IF UPDATE(pet_id)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Pet_Id', d.pet_id, i.pet_id
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.pet_id <> i.pet_id;


       IF UPDATE(staff_id)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Appointments', 'UPDATE', i.appointment_id, 'Staff_Id', d.staff_id, i.staff_id
           FROM deleted d JOIN inserted i ON d.appointment_id = i.appointment_id
           WHERE d.staff_id <> i.staff_id;
   END


   IF @Action = 'DELETE'
   BEGIN
       INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
       SELECT 'Appointments', 'DELETE', appointment_id,
              CONCAT('Appointment_Date: ', appointment_date, '; Appointment_Time: ', appointment_time, '; Reason: ', reason,
                     '; Status: ', status, '; Client_Id: ', client_id, '; Pet_Id: ', pet_id, '; Staff_Id: ', staff_id)
       FROM deleted;
   END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_Medical_Records]...';



GO
CREATE TRIGGER TRIGGER_ALL_Medical_Records ON Medical_Records
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
   SET NOCOUNT ON;
   DECLARE @Action VARCHAR(20);
   IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
       SET @Action = 'UPDATE';
   ELSE IF EXISTS (SELECT 1 FROM inserted)
       SET @Action = 'INSERT';
   ELSE
       SET @Action = 'DELETE';


   IF @Action = 'INSERT'
   BEGIN
       INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
       SELECT 'Medical_Records', 'INSERT', record_id,
              CONCAT('Visit_Date: ', visit_date, '; Diagnosis: ', ISNULL(diagnosis,''), '; Weight_Kg: ', weight_kg,
                     '; Notes: ', ISNULL(notes,''), '; Created_At: ', created_at, '; Pet_Id: ', pet_id, '; Staff_Id: ', staff_id)
       FROM inserted;
   END


   IF @Action = 'UPDATE'
   BEGIN
       IF UPDATE(visit_date)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Visit_Date', d.visit_date, i.visit_date
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE d.visit_date <> i.visit_date;


       IF UPDATE(diagnosis)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Diagnosis', d.diagnosis, i.diagnosis
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE ISNULL(d.diagnosis,'') <> ISNULL(i.diagnosis,'');


       IF UPDATE(weight_kg)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Weight_Kg', d.weight_kg, i.weight_kg
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE d.weight_kg <> i.weight_kg;


       IF UPDATE(notes)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Notes', d.notes, i.notes
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE ISNULL(d.notes,'') <> ISNULL(i.notes,'');


       IF UPDATE(created_at)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Created_At', d.created_at, i.created_at
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE d.created_at <> i.created_at;
          IF UPDATE(pet_id)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Pet_Id', d.pet_id, i.pet_id
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE d.pet_id <> i.pet_id;


       IF UPDATE(staff_id)
           INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
           SELECT 'Medical_Records', 'UPDATE', i.record_id, 'Staff_Id', d.staff_id, i.staff_id
           FROM deleted d JOIN inserted i ON d.record_id = i.record_id
           WHERE d.staff_id <> i.staff_id;
   END


   IF @Action = 'DELETE'
   BEGIN
       INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
       SELECT 'Medical_Records', 'DELETE', record_id,
              CONCAT('Visit_Date: ', visit_date, '; Diagnosis: ', ISNULL(diagnosis,''), '; Weight_Kg: ', weight_kg,
                     '; Notes: ', ISNULL(notes,''), '; Created_At: ', created_at, '; Pet_Id: ', pet_id, '; Staff_Id: ', staff_id)
       FROM deleted;
   END
END
GO
PRINT N'Creating Trigger [dbo].[TRIGGER_ALL_VaccinationSchedule]...';

GO
CREATE TRIGGER TRIGGER_ALL_VaccinationSchedule ON Vaccination_Schedule
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @Action VARCHAR(20);

    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
        SET @Action = 'UPDATE';
    ELSE IF EXISTS (SELECT 1 FROM inserted)
        SET @Action = 'INSERT';
    ELSE
        SET @Action = 'DELETE';

    IF @Action = 'INSERT'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, new_value)
        SELECT 'Vaccination_Schedule', 'INSERT', schedule_id,
               CONCAT('VaccineName: ', vaccine_name, '; LastGiven: ', last_given,
                      '; NextDue: ', next_due, '; ReminderSent: ', reminder_sent,
                      '; PetID: ', pet_id, '; RecordID: ', record_id)
        FROM inserted;
    END

    IF @Action = 'UPDATE'
    BEGIN
        IF UPDATE(vaccine_name)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Vaccination_Schedule', 'UPDATE', i.schedule_id, 'vaccine_name', d.vaccine_name, i.vaccine_name
            FROM deleted d JOIN inserted i ON d.schedule_id = i.schedule_id
            WHERE d.vaccine_name <> i.vaccine_name;

        IF UPDATE(last_given)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Vaccination_Schedule', 'UPDATE', i.schedule_id, 'last_given',
                   CONVERT(VARCHAR, d.last_given, 120), CONVERT(VARCHAR, i.last_given, 120)
            FROM deleted d JOIN inserted i ON d.schedule_id = i.schedule_id
            WHERE d.last_given <> i.last_given;

        IF UPDATE(next_due)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Vaccination_Schedule', 'UPDATE', i.schedule_id, 'next_due',
                   CONVERT(VARCHAR, d.next_due, 120), CONVERT(VARCHAR, i.next_due, 120)
            FROM deleted d JOIN inserted i ON d.schedule_id = i.schedule_id
            WHERE d.next_due <> i.next_due;

        IF UPDATE(reminder_sent)
            INSERT INTO AuditLog (table_name, operation_type, record_id, column_changed, old_value, new_value)
            SELECT 'Vaccination_Schedule', 'UPDATE', i.schedule_id, 'reminder_sent', d.reminder_sent, i.reminder_sent
            FROM deleted d JOIN inserted i ON d.schedule_id = i.schedule_id
            WHERE d.reminder_sent <> i.reminder_sent;
    END

    IF @Action = 'DELETE'
    BEGIN
        INSERT INTO AuditLog (table_name, operation_type, record_id, old_value)
        SELECT 'Vaccination_Schedule', 'DELETE', schedule_id,
               CONCAT('VaccineName: ', vaccine_name, '; LastGiven: ', last_given,
                      '; NextDue: ', next_due, '; ReminderSent: ', reminder_sent,
                      '; PetID: ', pet_id, '; RecordID: ', record_id)
        FROM deleted;
    END
END
GO
PRINT N'Creating View [dbo].[AllMedicationsView]...';


GO
CREATE VIEW AllMedicationsView AS
SELECT
    medication_id,
    drug_name,
    standard_dosage,
    unit,
    description
FROM Medications;
GO
PRINT N'Creating View [dbo].[AllStaffView]...';


GO

CREATE VIEW AllStaffView AS
SELECT
    staff_id,
    CONCAT(first_name, ' ', last_name) AS staff_name,
    role,
    email,
    phone,
    license_number,
    is_active
FROM Staff;
GO
PRINT N'Creating View [dbo].[PetsMedicalHistoryView]...';


GO
CREATE VIEW [dbo].[PetsMedicalHistoryView]
AS
    SELECT 
        mr.pet_id,
        mr.visit_date AS Date_Visited,
        mr.diagnosis AS Findings,
        mr.weight_kg AS Pet_Weight,
        mr.notes,
        m.drug_name AS Medicine,
        p.dosage_given AS Dosage,
        CONCAT(p.Instructions, ', take it for ', p.duration_days, ' day/s') AS Instructions,
        s.first_name + ' ' + s.last_name AS Examined_by,
        s.role, 
        s.license_number
    FROM Prescriptions p JOIN Medications m 
    ON p.medication_id = m.medication_id JOIN Medical_Records mr 
    ON p.record_id = mr.record_id JOIN Staff s
    ON mr.staff_id = s.staff_id
GO
PRINT N'Creating View [dbo].[PetsMedicalRecordsView]...';


GO
CREATE VIEW [dbo].[PetsMedicalRecordsView]
AS
    SELECT 
        mr.visit_date AS Date_Visited,
        mr.record_id AS Record_ID,
        mr.pet_id AS Pet_ID,
        p.name AS Pet_Name,
        mr.diagnosis AS Findings,
        mr.created_at AS Date_Created,
        CONCAT(s.first_name, ' ', s.last_name) AS Examined_by
    FROM Medical_Records mr JOIN Staff s
    ON mr.staff_id = s.staff_id JOIN Pets p 
    ON mr.pet_id = p.pet_id
GO
PRINT N'Creating View [dbo].[PrescriptionsView]...';


GO
CREATE VIEW PrescriptionsView AS
SELECT
    pr.prescription_id,
    pr.record_id,
    m.drug_name,
    pr.dosage_given,
    pr.duration_days,
    pr.instructions
FROM Prescriptions pr
JOIN Medications m ON pr.medication_id = m.medication_id;
GO
PRINT N'Creating View [dbo].[StaffWorkloadView]...';


GO
CREATE VIEW StaffWorkloadView AS
SELECT
    s.staff_id,
    CONCAT(s.first_name, ' ', s.last_name) AS staff_name,
    s.role,
    COUNT(a.appointment_id) AS total_appointments,
    SUM(CASE WHEN a.status = 'Scheduled' THEN 1 ELSE 0 END) AS scheduled_count,
    SUM(CASE WHEN a.status = 'Completed' THEN 1 ELSE 0 END) AS completed_count,
    SUM(CASE WHEN a.status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_count
FROM Staff s
LEFT JOIN Appointments a ON s.staff_id = a.staff_id
WHERE s.is_active = 1
GROUP BY s.staff_id, s.first_name, s.last_name, s.role;
GO
PRINT N'Creating View [dbo].[UpcomingAppointmentsView]...';


GO
CREATE VIEW [dbo].[UpcomingAppointmentsView]
AS
SELECT 
    p.pet_id,
    p.name AS pet_name, 
    p.species,
    CONCAT(c.first_name,' ',c.last_name) AS owner_name, 
    c.phone_number,
    a.appointment_date, 
    a.appointment_time,
    a.reason, 
    CONCAT(s.first_name,' ',s.last_name) AS Examiner, 
    a.status
FROM Appointments a JOIN Pets p 
ON a.pet_id = p.pet_id JOIN Clients c 
ON a.client_id = c.client_id JOIN Staff s 
ON a.staff_id = s.staff_id
WHERE a.appointment_date >= CAST(GETDATE() AS DATE)
GO
PRINT N'Creating View [dbo].[VaccinationScheduleView]...';


GO
CREATE VIEW [dbo].[VaccinationScheduleView]
AS
    SELECT 
        p.pet_id,
        p.name,
        p.breed,
        vs.vaccine_name AS Type_of_Vaccine,
        vs.next_due AS Vaccine_Due_Date,
        vs.reminder_sent,
        DATEDIFF(day, GETDATE(), vs.next_due ) AS Remaining_days_before_Due
    FROM Pets p JOIN Vaccination_Schedule vs 
    ON p.pet_id = vs.pet_id
GO
PRINT N'Creating Function [dbo].[CalculateNextVaccineDueDate]...';


GO
CREATE FUNCTION CalculateNextVaccineDueDate
(
@last_given date,
@interval_months SMALLINT
)
RETURNS date
AS
BEGIN
	DECLARE @due_date date
	SELECT
	@due_date = DATEADD(MONTH, @interval_months, @last_given)
	RETURN @due_date
END
GO
PRINT N'Creating Function [dbo].[GetPetAge]...';


GO

CREATE FUNCTION GetPetAge(@pet_id INT)
RETURNS INT
AS
BEGIN
	DECLARE @age INT
	SELECT
		@age = DATEDIFF(YEAR, birthdate, GETDATE())
	FROM Pets
	WHERE pet_id = @pet_id
	RETURN @age
END
GO
PRINT N'Creating Function [dbo].[IsSlotAvailable]...';


GO
CREATE FUNCTION IsSlotAvailable
(
@staff_id int,
@date date,
@time time(0)
)
RETURNS varchar(50)
AS
BEGIN
	DECLARE @slot varchar(50) = 'Available'

    IF EXISTS (
        SELECT 1 FROM Appointments
        WHERE staff_id = @staff_id
            AND appointment_date = @date
            AND appointment_time = @time
            AND status <> 'Cancelled'
    )
    BEGIN   
        SET @slot = 'Booked'
    END 

    RETURN @slot
END
GO
PRINT N'Creating View [dbo].[ActiveClientsAndPetsView]...';


GO
CREATE VIEW [dbo].[ActiveClientsAndPetsView]
AS
    SELECT  
       c.first_name + ' ' + c.last_name AS client_name,
       c.phone_number,
       p.name AS pet_name, 
       p.species, 
       p.breed, 
       p.sex, 
       dbo.GetPetAge(p.pet_id) AS age,
       p.Is_active AS Status
    FROM Clients c JOIN Pets p 
    ON c.client_id = p.client_id
    WHERE Is_active = 1
GO
PRINT N'Creating View [dbo].[ClientsPetsView]...';


GO
CREATE VIEW ClientsPetsView
AS
SELECT
      c.first_name + ' ' + c.last_name AS client_name,
      c.phone_number,
      p.name AS pet_name, 
      p.species, 
      p.breed, 
      p.sex,
      dbo.GetPetAge(p.pet_id) AS age
FROM Clients c JOIN Pets p
ON c.client_id = p.client_id
GO
PRINT N'Creating Procedure [dbo].[uspAddAppointment]...';


GO
CREATE PROC uspAddAppointment
    @Date DATE,
    @Time TIME,
    @Reason VARCHAR(MAX),
    @Status VARCHAR(50) = 'Scheduled',
    @ClientID INT,
    @PetID INT,
    @StaffID INT
AS 
BEGIN

    SET NOCOUNT ON;
    
    DECLARE @SlotStatus VARCHAR(50)
    SELECT @SlotStatus = dbo.IsSlotAvailable(@StaffID, @Date, @Time)

    IF @SlotStatus = 'Booked'
    BEGIN
        RAISERROR('This staff member already has an appointment at this date and time.', 16, 1)
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION


        INSERT Appointments
        VALUES (@Date, @Time, @Reason, @Status, @ClientID, @PetID, @StaffID)


        COMMIT TRANSACTION
        PRINT 'Appointment successfully created'
    END TRY

    BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH

END
GO
PRINT N'Creating Procedure [dbo].[uspAddMedicalRecord]...';


GO
CREATE PROC uspAddMedicalRecord
    @AppointmentID INT,
    @VisitDate     DATE,
    @Findings      VARCHAR(MAX),
    @Petweight     DECIMAL(5,2),
    @Remarks       VARCHAR(MAX),
    @DateCreated   DATETIME2(0) = NULL,
    @PetID         INT,
    @StaffID       INT
AS
BEGIN
    SET NOCOUNT ON;

    SET @DateCreated = ISNULL(@DateCreated, GETDATE());

    IF NOT EXISTS (SELECT 1 FROM Pets WHERE pet_id = @PetID)
    BEGIN
        RAISERROR('Pet does not exist.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM Staff WHERE staff_id = @StaffID)
    BEGIN
        RAISERROR('Staff does not exist.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM Appointments WHERE appointment_id = @AppointmentID)
    BEGIN
        RAISERROR('Appointment does not exist.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS ( SELECT 1 FROM Appointments WHERE appointment_id = @AppointmentID AND pet_id = @PetID )
    BEGIN
        RAISERROR('This pet is not linked to the specified appointment.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO Medical_Records (visit_date, diagnosis, weight_kg, notes, created_at, pet_id, staff_id)
        VALUES (@VisitDate, @Findings, @Petweight, @Remarks, @DateCreated, @PetID, @StaffID);

        DECLARE @RecordID INT = SCOPE_IDENTITY();

        UPDATE Appointments
        SET [status] = 'Completed'
        WHERE appointment_id = @AppointmentID
          AND [status] = 'Scheduled';

        COMMIT TRANSACTION
        PRINT CONCAT('Medical Record #', @RecordID, ' created successfully.');
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspAddMedication]...';


GO
CREATE PROC uspAddMedication
    @DrugName       VARCHAR(100),
    @StandardDosage VARCHAR(100),
    @Unit           VARCHAR(50),
    @Description    VARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    -- Prevent duplicate drug names (matches your UK_Medications_drugname constraint)
    IF EXISTS (SELECT medication_id FROM Medications WHERE drug_name = @DrugName)
    BEGIN
        RAISERROR('A medication with this name already exists.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO Medications (drug_name, standard_dosage, unit, description)
        VALUES (@DrugName, @StandardDosage, @Unit, @Description);

        COMMIT TRANSACTION
        PRINT 'Medication successfully added.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspAddNewStaff]...';


GO
CREATE PROC uspAddNewStaff
    @Fname VARCHAR(50),
    @Lname VARCHAR(50),
    @Role VARCHAR(50),
    @Email VARCHAR(50),
    @Phone CHAR(11),
    @License VARCHAR(50) = NULL,
    @IsActive BIT = NULL
AS
BEGIN

   IF LEFT(LTRIM(@Phone), 1) = '0'
        SET @Phone = SUBSTRING(LTRIM(@Phone), 2, LEN(@Phone));
    SET @Phone = LTRIM(RTRIM(@Phone));
   
    SET @IsActive = ISNULL(@IsActive, 1);

    INSERT Staff
    VALUES (@Fname, @Lname, @Role, @Email, @Phone, @License, @IsActive)

END
GO
PRINT N'Creating Procedure [dbo].[uspAddPrescription]...';


GO
CREATE PROC uspAddPrescription
    @RecordID     INT,
    @MedID        INT,
    @MedDosage    VARCHAR(50),
    @Duration     SMALLINT,
    @Instructions VARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Medical_Records WHERE record_id = @RecordID)
    BEGIN
        RAISERROR('Medical record does not exist.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT 1 FROM Medications WHERE medication_id = @MedID)
    BEGIN
        RAISERROR('Medicine does not exist.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO Prescriptions (dosage_given, duration_days, instructions, record_id, medication_id)
        VALUES (@MedDosage, @Duration, @Instructions, @RecordID, @MedID);

        COMMIT TRANSACTION
        PRINT 'Prescription successfully added.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspAddVaccinationSchedule]...';


GO
CREATE PROC uspAddVaccinationSchedule
    @VaccineName VARCHAR(50),
    @LastGiven   DATE,
    @Interval_Months SMALLINT,
    @PetID       INT,
    @RecordID    INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT pet_id FROM Pets WHERE pet_id = @PetID)
    BEGIN
        RAISERROR('Pet does not exist.', 16, 1);
        RETURN;
    END

    IF NOT EXISTS (SELECT record_id FROM Medical_Records WHERE record_id = @RecordID)
    BEGIN
        RAISERROR('Medical record does not exist.', 16, 1);
        RETURN;
    END

    -- Make sure the record actually belongs to this pet (prevents mismatched linking)
    IF NOT EXISTS (SELECT 1 FROM Medical_Records WHERE record_id = @RecordID AND pet_id = @PetID)
    BEGIN
        RAISERROR('This medical record does not belong to the specified pet.', 16, 1);
        RETURN;
    END

    IF @Interval_Months = 0
    BEGIN 
        RAISERROR('Interval should be greater than 0', 16, 1)
        RETURN
    END

    DECLARE @NextDue DATE = dbo.CalculateNextVaccineDueDate (@LastGiven, @Interval_Months)

    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO Vaccination_Schedule (vaccine_name, last_given, next_due, reminder_sent, pet_id, record_id)
        VALUES (@VaccineName, @LastGiven, @NextDue, 0, @PetID, @RecordID);

        COMMIT TRANSACTION
        PRINT 'Vaccination schedule successfully created.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspCancelAppointment]...';


GO

CREATE PROC uspCancelAppointment
    @AppointmentID INT
AS
BEGIN
    SET NOCOUNT ON;

    -- Make sure the appointment actually exists
    IF NOT EXISTS (SELECT 1 FROM Appointments WHERE appointment_id = @AppointmentID)
    BEGIN
        RAISERROR('Appointment does not exist.', 16, 1);
        RETURN;
    END

    -- Prevent cancelling something already completed or already cancelled
    DECLARE @CurrentStatus VARCHAR(50);
    SELECT @CurrentStatus = status FROM Appointments WHERE appointment_id = @AppointmentID;

    IF @CurrentStatus = 'Completed'
    BEGIN
        RAISERROR('Cannot cancel an appointment that is already Completed.', 16, 1);
        RETURN;
    END

    IF @CurrentStatus = 'Cancelled'
    BEGIN
        RAISERROR('This appointment is already Cancelled.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE Appointments
        SET status = 'Cancelled'
        WHERE appointment_id = @AppointmentID;

        COMMIT TRANSACTION
        PRINT 'Appointment successfully cancelled.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspDeleteClientPets]...';


GO
CREATE PROC uspDeleteClientPets
    @ClientID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT client_id FROM Clients WHERE client_id = @ClientID)
    BEGIN
        RAISERROR('Client doesnt exist.', 16, 1);
        RETURN
    END

    BEGIN TRY
        BEGIN TRANSACTION;

        DELETE FROM Pets 
        WHERE client_id = @ClientID;

        DELETE FROM Clients 
        WHERE client_id = @ClientID;

        COMMIT TRANSACTION;
        PRINT 'Client and associated pets deleted successfully.';
    END TRY

    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspDeleteMedicalRecord]...';


GO
CREATE PROC uspDeleteMedicalRecord
    @RecordID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Medical_Records WHERE record_id = @RecordID)
    BEGIN
        RAISERROR('Medical record does not exist.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        -- Remove dependent prescriptions first (cascade), since a medical record
        -- can't be deleted while prescriptions still reference it
        DELETE FROM Prescriptions
        WHERE record_id = @RecordID;

        DELETE FROM Medical_Records
        WHERE record_id = @RecordID;

        COMMIT TRANSACTION
        PRINT 'Medical record and its associated prescription(s) successfully deleted.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspDeleteMedication]...';


GO
CREATE PROC uspDeleteMedication
    @MedicationID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT medication_id FROM Medications WHERE medication_id = @MedicationID)
    BEGIN
        RAISERROR('Medication does not exist.', 16, 1);
        RETURN;
    END

    -- Prevent deleting a medication that's still referenced by existing prescriptions
    IF EXISTS (SELECT prescription_id FROM Prescriptions WHERE medication_id = @MedicationID)
    BEGIN
        RAISERROR('Cannot delete: this medication is referenced by existing prescriptions.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        DELETE FROM Medications
        WHERE medication_id = @MedicationID;

        COMMIT TRANSACTION
        PRINT 'Medication successfully deleted.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspDeletePrescription]...';


GO
CREATE PROC uspDeletePrescription
    @PrescriptionID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Prescriptions WHERE prescription_id = @PrescriptionID)
    BEGIN
        RAISERROR('Prescription does not exist.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        DELETE FROM Prescriptions
        WHERE prescription_id = @PrescriptionID;

        COMMIT TRANSACTION
        PRINT 'Prescription successfully deleted.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspDeleteVaccinationSchedule]...';


GO
CREATE PROC [dbo].[uspDeleteVaccinationSchedule]
    @ScheduleID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Vaccination_Schedule WHERE schedule_id = @ScheduleID)
    BEGIN
        RAISERROR('Vaccination schedule does not exist.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        DELETE FROM Vaccination_Schedule
        WHERE schedule_id = @ScheduleID;

        COMMIT TRANSACTION
        PRINT 'Vaccination schedule successfully deleted.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspInsertClientsPets]...';


GO
CREATE TYPE PetList AS TABLE
(
   PetName    VARCHAR(50),
   PetSpecies VARCHAR(50),
   PetBreed   VARCHAR(50) NULL,
   PetGender  CHAR(1),
   PetDOB     DATE
);
GO

GO
CREATE PROC uspInsertClientsPets
    @Fname      VARCHAR(50),
    @Lname      VARCHAR(50),
    @Email      VARCHAR(50),
    @Phone      CHAR(11),
    @Address    VARCHAR(MAX) = NULL,
    @Registered DATETIME = NULL,
    @Pets       PetList READONLY,
    @IsActive   BIT = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF LEFT(@Phone, 1) = '0'
    BEGIN
        SET @Phone = SUBSTRING(@Phone, 2, LEN(@Phone));
    END

    SET @IsActive = ISNULL(@IsActive, 1);
    SET @Registered = ISNULL(@Registered, GETDATE());

    BEGIN TRY
        BEGIN TRANSACTION

        INSERT INTO Clients (first_name, last_name, email, phone_number, address, registered_at)
        VALUES (@Fname, @Lname, @Email, @Phone, @Address, @Registered);

        DECLARE @OwnerID INT = SCOPE_IDENTITY();

        INSERT INTO Pets (name, species, breed, sex, birthdate, is_active, client_id)
        SELECT PetName, PetSpecies, PetBreed, PetGender, PetDOB, @IsActive, @OwnerID
        FROM @Pets;

        DECLARE @PetCount INT = (SELECT COUNT(*) FROM @Pets);

        COMMIT TRANSACTION
        PRINT CONCAT('Client and ', @PetCount, ' pet(s) inserted successfully.');
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        THROW;
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspSoftDeleteStaff]...';


GO
CREATE PROC uspSoftDeleteStaff
    @StaffID INT
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT staff_id FROM Staff WHERE staff_id = @StaffID)
    BEGIN
        RAISERROR('Staff member does not exist.', 16, 1);
        RETURN
    END
  
    IF EXISTS (SELECT staff_id FROM Staff WHERE staff_id = @StaffID AND is_active = 0)
    BEGIN
        RAISERROR('Staff member is already inactive.', 16, 1);
        RETURN
    END

    BEGIN TRY
        UPDATE Staff
        SET is_active = 0
        WHERE staff_id = @StaffID;

        PRINT 'Staff member successfully deactivated.';
    END TRY
    BEGIN CATCH
       PRINT(ERROR_MESSAGE())
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateAppointment]...';


GO
CREATE PROC uspUpdateAppointment
    @AppointmentID INT,
    @Date          DATE         = NULL,
    @Time          TIME         = NULL,
    @Reason        VARCHAR(MAX) = NULL,
    @Status        VARCHAR(50)  = NULL,
    @StaffID       INT          = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Appointments WHERE appointment_id = @AppointmentID)
    BEGIN
        RAISERROR('Appointment does not exist.', 16, 1);
        RETURN;
    END

    -- Get the current values, so we know what's ACTUALLY changing
    DECLARE @CurrentDate    DATE;
    DECLARE @CurrentTime    TIME;
    DECLARE @CurrentStaffID INT;

    SELECT
        @CurrentDate    = appointment_date,
        @CurrentTime    = appointment_time,
        @CurrentStaffID = staff_id
    FROM Appointments
    WHERE appointment_id = @AppointmentID;

    DECLARE @EffectiveDate    DATE = ISNULL(@Date, @CurrentDate);
    DECLARE @EffectiveTime    TIME = ISNULL(@Time, @CurrentTime);
    DECLARE @EffectiveStaffID INT  = ISNULL(@StaffID, @CurrentStaffID);

    -- Only re-check slot availability if date, time, or staff actually changed
    IF (@Date IS NOT NULL OR @Time IS NOT NULL OR @StaffID IS NOT NULL)
    BEGIN
        IF EXISTS (
            SELECT 1 FROM Appointments
            WHERE staff_id = @EffectiveStaffID
              AND appointment_date = @EffectiveDate
              AND appointment_time = @EffectiveTime
              AND status <> 'Cancelled'
              AND appointment_id <> @AppointmentID   -- exclude the appointment being updated itself
        )
        BEGIN
            RAISERROR('This staff member already has an appointment at this date and time.', 16, 1);
            RETURN;
        END
    END

    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE Appointments
        SET appointment_date = @EffectiveDate,
            appointment_time = @EffectiveTime,
            reason           = ISNULL(@Reason, reason),
            status           = ISNULL(@Status, status),
            staff_id         = @EffectiveStaffID
        WHERE appointment_id = @AppointmentID;

        COMMIT TRANSACTION
        PRINT 'Appointment updated successfully.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateClientsPets]...';


GO
CREATE PROC [dbo].[uspUpdateClientsPets]
    @ClientID INT,
    @Fname VARCHAR(50) = NULL,
    @Lname VARCHAR(50) = NULL,
    @Email VARCHAR(50) = NULL,
    @Phone CHAR(11) = NULL,
    @Address VARCHAR(MAX) = NULL,
    @Registered DATETIME = NULL,
    @PetID INT = NULL,
    @PetName VARCHAR(50) = NULL,
    @PetSpecies VARCHAR(50) = NULL,
    @PetBreed VARCHAR(50) = NULL,
    @PetGender CHAR(1) = NULL,
    @PetDOB DATE = NULL,
    @IsActive BIT = NULL

 AS
 BEGIN 
    SET NOCOUNT ON;

     IF @Phone IS NOT NULL AND LEFT((@Phone), 1) = '0'
        BEGIN 
            SET @Phone = SUBSTRING(@Phone, 2, LEN(@Phone)); 
        END

    IF NOT EXISTS (SELECT client_id FROM Clients WHERE client_id = @ClientID)
    BEGIN
       RAISERROR('Client does not exist', 16, 1);
        RETURN;
    END

    IF @PetID IS NOT NULL 
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM Pets WHERE pet_id = @PetID AND client_id = @ClientID )
        BEGIN
            RAISERROR(' The specified Pet does not belong to this Client, or Client or Pet does not exist.', 16, 1);
            RETURN;
        END
    END
    
    BEGIN TRY
        BEGIN TRANSACTION

            UPDATE Clients
            SET first_name = ISNULL(@Fname, first_name),
                last_name = ISNULL(@Lname, last_name),
                email = ISNULL(@Email, email),
                phone_number = ISNULL(@Phone, phone_number),
                [address] = ISNULL(@Address, [address]),
                registered_at = ISNULL(@Registered, registered_at)
            WHERE client_id = @ClientID;

            IF @PetID IS NOT NULL
            BEGIN
                UPDATE Pets
                SET [name] = ISNULL(@PetName, [name]),
                    species = ISNULL(@PetSpecies, species),
                    breed = ISNULL(@PetBreed, breed),
                    sex = ISNULL(@PetGender, sex),
                    birthdate = ISNULL(@PetDOB, birthdate),
                    is_active = ISNULL(@IsActive, is_active)
                WHERE pet_id = @PetID;
            END 

            COMMIT TRANSACTION
            PRINT ('Records updated successfully.');

        END TRY

        BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
            PRINT(ERROR_MESSAGE());
        END CATCH
 END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateMedicalRecord]...';


GO
CREATE PROC uspUpdateMedicalRecord
    @RecordID  INT,
    @VisitDate DATE         = NULL,
    @Findings  VARCHAR(MAX) = NULL,
    @Petweight DECIMAL(5,2) = NULL,
    @Remarks   VARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Medical_Records WHERE record_id = @RecordID)
    BEGIN
        RAISERROR('Medical record does not exist.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE Medical_Records
        SET visit_date = ISNULL(@VisitDate, visit_date),
            diagnosis  = ISNULL(@Findings, diagnosis),
            weight_kg  = ISNULL(@Petweight, weight_kg),
            notes      = ISNULL(@Remarks, notes)
        WHERE record_id = @RecordID;

        COMMIT TRANSACTION
        PRINT 'Medical record updated successfully.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateMedication]...';


GO
CREATE PROC uspUpdateMedication
    @MedicationID   INT,
    @DrugName       VARCHAR(100) = NULL,
    @StandardDosage VARCHAR(100) = NULL,
    @Unit           VARCHAR(50)  = NULL,
    @Description    VARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT medication_id FROM Medications WHERE medication_id = @MedicationID)
    BEGIN
        RAISERROR('Medication does not exist.', 16, 1);
        RETURN;
    END

    -- If the caller is trying to rename it, make sure the new name isn't already taken by another row
    IF @DrugName IS NOT NULL AND EXISTS (
        SELECT medication_id FROM Medications
        WHERE drug_name = @DrugName AND medication_id <> @MedicationID
    )
    BEGIN
        RAISERROR('Another medication already uses this name.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE Medications
        SET drug_name       = ISNULL(@DrugName, drug_name),
            standard_dosage = ISNULL(@StandardDosage, standard_dosage),
            unit            = ISNULL(@Unit, unit),
            description     = ISNULL(@Description, description)
        WHERE medication_id = @MedicationID;

        COMMIT TRANSACTION
        PRINT 'Medication successfully updated.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspUpdatePrescription]...';


GO
CREATE PROC uspUpdatePrescription
    @PrescriptionID INT,
    @MedID          INT          = NULL,
    @MedDosage      VARCHAR(50)  = NULL,
    @Duration       SMALLINT     = NULL,
    @Instructions   VARCHAR(MAX) = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Prescriptions WHERE prescription_id = @PrescriptionID)
    BEGIN
        RAISERROR('Prescription does not exist.', 16, 1);
        RETURN;
    END

    IF @MedID IS NOT NULL AND NOT EXISTS (SELECT 1 FROM Medications WHERE medication_id = @MedID)
    BEGIN
        RAISERROR('Medicine does not exist.', 16, 1);
        RETURN;
    END

    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE Prescriptions
        SET medication_id = ISNULL(@MedID, medication_id),
            dosage_given  = ISNULL(@MedDosage, dosage_given),
            duration_days = ISNULL(@Duration, duration_days),
            instructions  = ISNULL(@Instructions, instructions)
        WHERE prescription_id = @PrescriptionID;

        COMMIT TRANSACTION
        PRINT 'Prescription updated successfully.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateStaff]...';


GO
CREATE PROC uspUpdateStaff
    @StaffID INT,
    @Fname VARCHAR(50) = NULL,
    @Lname VARCHAR(50) = NULL,
    @Role VARCHAR(50) = NULL,
    @Email VARCHAR(50) = NULL,
    @Phone CHAR(11) = NULL,
    @License VARCHAR(50) = NULL,
    @IsActive BIT = NULL
AS
BEGIN

    SET NOCOUNT ON

    IF NOT EXISTS (SELECT staff_id FROM Staff WHERE staff_id = @StaffID)
    BEGIN
        RAISERROR('Staff does not exists', 16, 1)
    END

     IF @Phone IS NOT NULL
    BEGIN
        IF LEFT(LTRIM(@Phone), 1) = '0'
        BEGIN 
            SET @Phone = SUBSTRING(LTRIM(@Phone), 2, LEN(@Phone));
        END
        SET @Phone = LTRIM(RTRIM(@Phone));
    END

    BEGIN TRY
        BEGIN TRANSACTION
    
            UPDATE Staff
            SET 
                first_name = ISNULL(@Fname, first_name),
                last_name = ISNULL(@Lname, last_name),
                role = ISNULL(@Role, role),
                email = ISNULL(@Email, email),
                phone = ISNULL(@Phone, phone),
                license_number = ISNULL(@License, license_number),
                is_active = ISNULL(@IsActive, is_active)
            WHERE staff_id = @StaffID

        COMMIT TRANSACTION
        PRINT 'Staff successfully updated'
    END TRY

    BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION
        PRINT(ERROR_MESSAGE())
    END CATCH

END
GO
PRINT N'Creating Procedure [dbo].[uspUpdateVaccinationSchedule]...';


GO
CREATE PROC [dbo].[uspUpdateVaccinationSchedule]
    @ScheduleID      INT,
    @VaccineName     VARCHAR(50)  = NULL,
    @LastGiven       DATE         = NULL,
    @Interval_Months SMALLINT     = NULL
AS
BEGIN
    SET NOCOUNT ON;

    IF NOT EXISTS (SELECT 1 FROM Vaccination_Schedule WHERE schedule_id = @ScheduleID)
    BEGIN
        RAISERROR('Vaccination schedule does not exist.', 16, 1);
        RETURN;
    END

    IF @Interval_Months = 0
    BEGIN
        RAISERROR('Interval should be greater than 0', 16, 1);
        RETURN;
    END

    -- Get the CURRENT last_given, in case only the interval is being changed (or vice versa)
    DECLARE @CurrentLastGiven DATE;
    SELECT @CurrentLastGiven = last_given FROM Vaccination_Schedule WHERE schedule_id = @ScheduleID;

    -- Use whichever value was provided, otherwise fall back to the existing one
    DECLARE @EffectiveLastGiven DATE = ISNULL(@LastGiven, @CurrentLastGiven);

    -- Only recalculate next_due if last_given OR interval actually changed
    DECLARE @NextDue DATE;
    IF @LastGiven IS NOT NULL OR @Interval_Months IS NOT NULL
    BEGIN
        -- Need an interval to recalculate; if none was passed this time, we can't safely recompute
        IF @Interval_Months IS NULL
        BEGIN
            RAISERROR('Interval_Months is required when updating LastGiven, to recalculate NextDue.', 16, 1);
            RETURN;
        END

        SET @NextDue = dbo.CalculateNextVaccineDueDate(@EffectiveLastGiven, @Interval_Months);
    END

    BEGIN TRY
        BEGIN TRANSACTION

        UPDATE Vaccination_Schedule
        SET vaccine_name = ISNULL(@VaccineName, vaccine_name),
            last_given    = ISNULL(@LastGiven, last_given),
            next_due      = ISNULL(@NextDue, next_due)
        WHERE schedule_id = @ScheduleID;

        COMMIT TRANSACTION
        PRINT 'Vaccination schedule updated successfully.';
    END TRY
    BEGIN CATCH
        IF @@TRANCOUNT > 0
            ROLLBACK TRANSACTION;
        PRINT(ERROR_MESSAGE());
    END CATCH
END
GO

PRINT N'Deployment complete.';
GO




